server:
  port: 8001

spring:
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1oj2fx4gn2k5dx3jo.mysql.rds.aliyuncs.com/ikun?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Tlp123456
    hikari:
    # 连接池名
    pool-name: DateHikariCP
    # 最小空闲连接数
    minimum-idle: 5
    # 空闲连接存活最大时间，默认600000（10分钟）
    idle-timeout: 180000
    # 最大连接数，默认10
    maximum-pool-size: 10
    # 从连接池返回的连接的自动提交
    auto-commit: true
    # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
    max-lifetime: 1800000
    # 连接超时时间，默认30000（30秒）
    connection-timeout: 30000
    # 测试连接是否可用的查询语句
    connection-test-query: SELECT 1

  redis:
    timeout: 10000ms
#    host: 81.71.130.95
    host: 127.0.0.1
    port: 6379
    database: 0 # 选择哪个库，默认0库
    time-to-live: 9000
    password:
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5

  #    password: cbb123..
  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host: 120.48.74.98
    # 端口
    port: 5672
    # 消息失败回调
    publisher-returns: true
    # 消息确认回调
    publisher-confirm-type: correlated

#  rabbitmq:
#    # 用户名
#    username: admin
#    # 密码
#    password: 123
#    # 服务器地址
#    host: 192.168.208.138
#    # 端口
#    port: 5672
#    listener:
#      simple:
#        # 手动确认
#        acknowledge-mode: manual


  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB



mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: org.example.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    org.example.mapper: debug


jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: ikun
  # Jwt 的超期限时间（60*60）*24
  expiration: 604800
  # Jwt负载中拿到开头
  tokenHead: Bearer


minio:
  endpoint: http://120.48.74.98:19000/
  bucketName: tlptlp
  accessKey: tlptlp
  secretKey: tlp123456
